theme: jekyll-theme-merlot
show_downloads: false
title: Hastol-Kampagnenübersicht
description: Eine kleine Übersicht über die Kampagne, zusammen mit Loot-table, Tagebuch und wissenswerten Dingen.
collections:
  relicts:
    output: true
  orga:
    output: true
