theme: jekyll-theme-merlot
show_downloads: false
title: Hastol-Kampagnenübersicht
description: Eine kleine Übersicht über die Kampagne, zusammen mit Loot-table, Tagebuch und wissenswerten Dingen.
collections:
  relics:
    output: true
  orga:
    output: true
  character:
    output: true
    permalink: /:collection/:name
relative_links:
  enabled: true
  collections: true
future: true
defaults:
  - scope:
      path: ""
      type: "relics"
    values:
      layout: "relics"
  - scope:
      path: ""
    values:
      layout: "default"
