theme: jekyll-theme-merlot
show_downloads: false
title: Hastol-Kampagnenübersicht
description: Eine kleine Übersicht über die Kampagne, zusammen mit Loot-table, Tagebuch und wissenswerten Dingen.
collections:
  relics:
    output: true
  lore:
    output: true
  characters:
    output: true
  npcs:
    output: true
relative_links:
  enabled: true
  collections: true
future: true
defaults:
  - scope:
      path: ""
      type: "relics"
    values:
      layout: "relics"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "characters"
  - scope:
      path: ""
      type: "npcs"
    values:
      layout: "npcs"
  - scope:
      path: ""
    values:
      layout: "default"
